services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
