spring:
  application:
    name: "schola-backbone-server"
  jpa:
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3307/schola
    username: root
    password: password
  hibernate:
    auto-ddl: update
  security:
    # This is a custom section i created for secure password's
    password:
      checker:
        secure: weak
